apiVersion: apps/v1
kind: Deployment
metadata:
  name: rielu-site
spec:
  selector:
    matchLabels:
      app: rielu-site
  replicas: 1
  template:
    metadata:
      labels:
        app: rielu-site
    spec:
      containers:
        - name: app
          image: docker.io/rieluinfra/rielu-site
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: default-port
          resources:
            requests:
              cpu: 500m # 必要最低限の0.5CPUを確保
              memory: 1Gi # 必要最低限の1GiBを確保
            limits:
              cpu: 1000m # 最大1CPUまで使用可能
              memory: 2Gi # 最大2GiBまで使用可能
          readinessProbe:
            initialDelaySeconds: 40
            periodSeconds: 30
            httpGet:
              path: /
              port: default-port
              httpHeaders:
                - name: X-k8s-Header
                  value: readiness
          env:
            - name: TZ
              value: Asia/Tokyo
