apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: unipro-site
  namespace: argocd
spec:
  namespace: argocd
  applicationRefs:
    - namePattern: "rielu-site"
      images:
        - alias: "rielu-site"
          imageName: "registry.rielu.uniproject.jp/official/rielu-site"
          commonUpdateSettings:
            updateStrategy: "semver"
