apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rielu-site
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: rielu-site=docker.io/rieluinfra/rielu-site
    argocd-image-updater.argoproj.io/rielu-site.update-strategy: semver
    argocd-image-updater.argoproj.io/write-back-method: git
