apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: rielu-site-updater
  namespace: argocd
spec:
  writeBackConfig:
    method: "git"
    gitConfig:
      repository: "https://github.com/rielu-s-infra/rielu-site.git"
      branch: "master"
      writeBackTarget: "helmvalues:./argoCD/values.yaml"
  applicationRefs:
    - namePattern: "rielu-site"
      images:
        - alias: "app"
          imageName: "docker.io/rieluinfra/rielu-site"
          commonUpdateSettings:
            updateStrategy: "latest"