apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: rielu-site
  namespace: rielu-site
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`rielu.uniproject.jp`) && PathPrefix(`/`)
      observability:
        accessLogs: true
        metrics: true
        tracing: true
      priority: 1
      services:
        - kind: Service
          name: rielu-site
          passHostHeader: true
          port: 3000
          sticky:
            cookie:
              httpOnly: true
              name: cookie
              secure: true
  tls:
    certResolver: cf-prod
    domains:
      - main: rielu.uniproject.jp