apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rielu-site
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - imageUpdater.yaml
  - hpa.yaml
labels:
  - includeSelectors: true
    pairs:
      app: rielu-site
